spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/twMall_microserver_order?characterEncoding=utf-8
    username: root
    password: yedili
  jpa:
    generate-ddl: true
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

