spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tw_orders?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    generate-ddl: true

server:
  port: 8082

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

